### PR TITLE
PosetChain

### PR DESCRIPTION
**Pull request by XintaoYu**

### CODE REVIEW

**Comment by XintaoYu** [comment]
Please do not merge until we finish all the proof in PosetChain.
If we finish it, we will inform you of it.

**Comment by XintaoYu** [comment]
finish all the proof in PosetChain but add one new lemma in AdjacentPair which needs to be proved

**Comment by XintaoYu** [comment]
already finish all the proof in PosetChain and AdjacentPair

**Comment by clarence-chew** [comment]
> Please do not merge until we finish all the proof in PosetChain. If we finish it, we will inform you of it.

In the future, you can use the "Draft pull request" feature for this (assuming you haven't this time).

**Comment by timechess** [comment]
It's safe to merge now.

**Review by JQChong — APPROVED** [review]

**Pull request merged**
